/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as PositionRouteImport } from './routes/position'
import { Route as PassagesRouteImport } from './routes/passages'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PrintQuizRouteImport } from './routes/print/quiz'
import { Route as PrintPosterRouteImport } from './routes/print/poster'
import { Route as PrintGlossaireRouteImport } from './routes/print/glossaire'
import { Route as PrintFichesRouteImport } from './routes/print/fiches'
import { Route as PrintColoriagesRouteImport } from './routes/print/coloriages'
import { Route as PrintCartesRouteImport } from './routes/print/cartes'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionRoute = PositionRouteImport.update({
  id: '/position',
  path: '/position',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagesRoute = PassagesRouteImport.update({
  id: '/passages',
  path: '/passages',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQuizRoute = PrintQuizRouteImport.update({
  id: '/print/quiz',
  path: '/print/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPosterRoute = PrintPosterRouteImport.update({
  id: '/print/poster',
  path: '/print/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintGlossaireRoute = PrintGlossaireRouteImport.update({
  id: '/print/glossaire',
  path: '/print/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintFichesRoute = PrintFichesRouteImport.update({
  id: '/print/fiches',
  path: '/print/fiches',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintColoriagesRoute = PrintColoriagesRouteImport.update({
  id: '/print/coloriages',
  path: '/print/coloriages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCartesRoute = PrintCartesRouteImport.update({
  id: '/print/cartes',
  path: '/print/cartes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/passages': typeof PassagesRoute
  '/position': typeof PositionRoute
  '/ressources': typeof RessourcesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/print/cartes': typeof PrintCartesRoute
  '/print/coloriages': typeof PrintColoriagesRoute
  '/print/fiches': typeof PrintFichesRoute
  '/print/glossaire': typeof PrintGlossaireRoute
  '/print/poster': typeof PrintPosterRoute
  '/print/quiz': typeof PrintQuizRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/passages': typeof PassagesRoute
  '/position': typeof PositionRoute
  '/ressources': typeof RessourcesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/print/cartes': typeof PrintCartesRoute
  '/print/coloriages': typeof PrintColoriagesRoute
  '/print/fiches': typeof PrintFichesRoute
  '/print/glossaire': typeof PrintGlossaireRoute
  '/print/poster': typeof PrintPosterRoute
  '/print/quiz': typeof PrintQuizRoute
  '/blog': typeof BlogIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/passages': typeof PassagesRoute
  '/position': typeof PositionRoute
  '/ressources': typeof RessourcesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/print/cartes': typeof PrintCartesRoute
  '/print/coloriages': typeof PrintColoriagesRoute
  '/print/fiches': typeof PrintFichesRoute
  '/print/glossaire': typeof PrintGlossaireRoute
  '/print/poster': typeof PrintPosterRoute
  '/print/quiz': typeof PrintQuizRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/live'
    | '/mentions-legales'
    | '/passages'
    | '/position'
    | '/ressources'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/print/cartes'
    | '/print/coloriages'
    | '/print/fiches'
    | '/print/glossaire'
    | '/print/poster'
    | '/print/quiz'
    | '/blog/'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/products'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/live'
    | '/mentions-legales'
    | '/passages'
    | '/position'
    | '/ressources'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/print/cartes'
    | '/print/coloriages'
    | '/print/fiches'
    | '/print/glossaire'
    | '/print/poster'
    | '/print/quiz'
    | '/blog'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/products'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/live'
    | '/mentions-legales'
    | '/passages'
    | '/position'
    | '/ressources'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/print/cartes'
    | '/print/coloriages'
    | '/print/fiches'
    | '/print/glossaire'
    | '/print/poster'
    | '/print/quiz'
    | '/blog/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  LiveRoute: typeof LiveRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PassagesRoute: typeof PassagesRoute
  PositionRoute: typeof PositionRoute
  RessourcesRoute: typeof RessourcesRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PrintCartesRoute: typeof PrintCartesRoute
  PrintColoriagesRoute: typeof PrintColoriagesRoute
  PrintFichesRoute: typeof PrintFichesRoute
  PrintGlossaireRoute: typeof PrintGlossaireRoute
  PrintPosterRoute: typeof PrintPosterRoute
  PrintQuizRoute: typeof PrintQuizRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position': {
      id: '/position'
      path: '/position'
      fullPath: '/position'
      preLoaderRoute: typeof PositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passages': {
      id: '/passages'
      path: '/passages'
      fullPath: '/passages'
      preLoaderRoute: typeof PassagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/quiz': {
      id: '/print/quiz'
      path: '/print/quiz'
      fullPath: '/print/quiz'
      preLoaderRoute: typeof PrintQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/poster': {
      id: '/print/poster'
      path: '/print/poster'
      fullPath: '/print/poster'
      preLoaderRoute: typeof PrintPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/glossaire': {
      id: '/print/glossaire'
      path: '/print/glossaire'
      fullPath: '/print/glossaire'
      preLoaderRoute: typeof PrintGlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/fiches': {
      id: '/print/fiches'
      path: '/print/fiches'
      fullPath: '/print/fiches'
      preLoaderRoute: typeof PrintFichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/coloriages': {
      id: '/print/coloriages'
      path: '/print/coloriages'
      fullPath: '/print/coloriages'
      preLoaderRoute: typeof PrintColoriagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/cartes': {
      id: '/print/cartes'
      path: '/print/cartes'
      fullPath: '/print/cartes'
      preLoaderRoute: typeof PrintCartesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  LiveRoute: LiveRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PassagesRoute: PassagesRoute,
  PositionRoute: PositionRoute,
  RessourcesRoute: RessourcesRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  PrintCartesRoute: PrintCartesRoute,
  PrintColoriagesRoute: PrintColoriagesRoute,
  PrintFichesRoute: PrintFichesRoute,
  PrintGlossaireRoute: PrintGlossaireRoute,
  PrintPosterRoute: PrintPosterRoute,
  PrintQuizRoute: PrintQuizRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
